[package]
name = "method"
version = "0.1.0"

[workspace]

[dependencies]
risc0-zkp = { version = "1.0.1", default-features = false }
risc0-zkvm = { version = "1.0.1", default-features = false, features = ['std'] }
issuer-core = {path = "./../../core"}