[package]
name = "issuer-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
risc0-zkp = { version = "1.0.1", default-features = false }
digest = "0.10.7"
hex = "0.4.3"