[package]
name = "issuer-core"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkp = { version = "1.0.2", default-features = false }
risc0-zkvm = { version = "1.0.2", default-features = false, features = ['std'] }

serde = { version = "1.0.204", features = ["derive"] }
hex = "0.4.3"